# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-06 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('priority', models.CharField(choices=[(3, 'HIGHER'), (2, 'MEDIUM'), (1, 'LOWER')], default=2, max_length=1)),
            ],
        ),
    ]
