# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-11 20:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0002_usertask'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserTask',
        ),
        migrations.AddField(
            model_name='task',
            name='created_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
