# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-18 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20180611_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.IntegerField(choices=[(3, b'HIGHER'), (2, b'MEDIUM'), (1, b'LOWER')], default=2, max_length=1),
        ),
    ]
